Repository JuliaHEP/JetReconstruction.jl, pull requests merged in 2025-07, with the labels that each got.

#175 Fix missing algorithm arg in examples in docstrings
  src/PlainAlgo.jl
  src/TiledAlgoLL.jl
Labels: documentation

#187 Fix type instability when passing type to a function, concretize default types
  README.md
  docs/src/softkiller.md
  examples/EDM4hep/EDM4hepJets.jl
  examples/EDM4hep/SimpleRecoEDM4hep.jl
  examples/constituents/jetreco-constituents-nb.jl
  examples/constituents/jetreco-constituents.jl
  examples/instrumented-jetreco.jl
  examples/jetreco.jl
  examples/softkiller/softkiller_plots.jl
  examples/softkiller/softkiller_runtime.jl
  examples/substructure/jet-grooming.jl
  examples/substructure/jet-tagging.jl
  src/ClusterSequence.jl
  src/CommonJetStructs.jl
  src/EEAlgorithm.jl
  src/PlainAlgo.jl
  src/Substructure.jl
  src/TiledAlgoLL.jl
  src/Utils.jl
  test/_common.jl
  test/data/hepmc32summary.jl
  test/test-compare-types.jl
  test/test-constituents.jl
  test/test-substructure.jl
Labels: interface change

#195 Internal function improvements
  src/EEAlgorithm.jl
  src/PlainAlgo.jl
  src/TiledAlgoLL.jl
Labels: Internals
